version: '3'

services:
  # PHP Application Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: coza-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-net
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: coza-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  dbdata:
    driver: local